export const FiguresArray = [
  // first row (black)
  {
    color: "black",
    active: true,
    positionX: 1,
    positionY: 1,
    combo: false,
  },
  {
    color: "black",
    active: true,
    positionX: 1,
    positionY: 3,
    combo: false,
  },
  {
    color: "black",
    active: true,
    positionX: 1,
    positionY: 5,
    combo: false,
  },
  {
    color: "black",
    active: true,
    positionX: 1,
    positionY: 7,
    combo: false,
  },
  // second row (black)
  {
    color: "black",
    active: true,
    positionX: 2,
    positionY: 0,
    combo: false,
  },
  {
    color: "black",
    active: true,
    positionX: 2,
    positionY: 2,
    combo: false,
  },
  {
    color: "black",
    active: true,
    positionX: 2,
    positionY: 4,
    combo: false,
  },
  {
    color: "black",
    active: true,
    positionX: 2,
    positionY: 6,
    combo: false,
  },
  // third row (black)
  {
    color: "black",
    active: true,
    positionX: 3,
    positionY: 1,
    combo: false,
  },
  {
    color: "black",
    active: true,
    positionX: 3,
    positionY: 3,
    combo: false,
  },
  {
    color: "black",
    active: true,
    positionX: 3,
    positionY: 5,
    combo: false,
  },
  {
    color: "black",
    active: true,
    positionX: 3,
    positionY: 7,
    combo: false,
  },

  // third row (white)
  {
    color: "white",
    active: true,
    positionX: 6,
    positionY: 0,
    combo: false,
  },
  {
    color: "white",
    active: true,
    positionX: 6,
    positionY: 2,
    combo: false,
  },
  {
    color: "white",
    active: true,
    positionX: 6,
    positionY: 4,
    combo: false,
  },
  {
    color: "white",
    active: true,
    positionX: 6,
    positionY: 6,
    combo: false,
  },
  // second row (white)
  {
    color: "white",
    active: true,
    positionX: 7,
    positionY: 1,
    combo: false,
  },
  {
    color: "white",
    active: true,
    positionX: 7,
    positionY: 3,
    combo: false,
  },
  {
    color: "white",
    active: true,
    positionX: 7,
    positionY: 5,
    combo: false,
  },
  {
    color: "white",
    active: true,
    positionX: 7,
    positionY: 7,
    combo: false,
  },
  // first row (white)
  {
    color: "white",
    active: true,
    positionX: 8,
    positionY: 0,
    combo: false,
  },
  {
    color: "white",
    active: true,
    positionX: 8,
    positionY: 2,
    combo: false,
  },
  {
    color: "white",
    active: true,
    positionX: 8,
    positionY: 4,
    combo: false,
  },
  {
    color: "white",
    active: true,
    positionX: 8,
    positionY: 6,
    combo: false,
  },
];
